# Generated by Django 4.0.dev20210707183257 on 2021-09-05 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('zip_code', models.CharField(max_length=30)),
                ('distance', models.CharField(default='Near', max_length=30)),
                ('headshot', models.ImageField(default='default.jpeg', upload_to='images/')),
                ('work_1', models.ImageField(default='default.jpeg', upload_to='images/')),
                ('work_2', models.ImageField(default='default.jpeg', upload_to='images/')),
                ('work_3', models.ImageField(default='default.jpeg', upload_to='images/')),
                ('rating', models.CharField(default='N/A', max_length=3)),
                ('testfield', models.CharField(default='N/A', max_length=3)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
