# Generated by Django 4.0.dev20210707183257 on 2021-09-05 18:24

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professional',
            name='testfield',
        ),
        migrations.AddField(
            model_name='professional',
            name='skills',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('mcut', "Men's Cut"), ('wcut', "Women's Cut"), ('col', 'Coloring'), ('wax', 'Waxing'), ('high', 'Highlights'), ('con', 'Conditioning'), ('bride', 'Bridal')], default='None', max_length=32),
        ),
    ]
