# Generated by Django 4.0.dev20210707183257 on 2021-09-17 15:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_remove_professional_testfield_professional_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='available_schedule',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=7), default=list, size=None),
        ),
    ]
